<?php

return [
    'USD' => 'U.S. Dollar',
    'AUD' => 'Australian Dollar',
    'BRL' => 'Brazilian Real',
    'CAD' => 'Canadian Dollar',
    'CZK' => 'Czech Koruna',
    'RUB' => 'Russian ruble',
    'DKK' => 'Danish Krone',
    'EUR' => 'Euro',
    'HKD' => 'Hong Kong Dollar',
    'HUF' => 'Hungarian Forint',
    'ILS' => 'Israeli New Sheqel',
    'INR' => 'Indian Rupee',
    'JPY' => 'Japanese Yen',
    'MYR' => 'Malaysian Ringgit',
    'MXN' => 'Mexican Peso',
    'NOK' => 'Norwegian Krone',
    'NZD' => 'New Zealand Dollar',
    'PHP' => 'Philippine Peso',
    'PLN' => 'Polish Zloty',
    'GBP' => 'Pound Sterling',
    'SGD' => 'Singapore Dollar',
    'SEK' => 'Swedish Krona',
    'CHF' => 'Swiss Franc',
    'TRY' => 'Turkish Lira',
    'TWD' => 'Taiwan New Dollar',
    'THB' => 'Thai Baht',
    'NGN' => 'Nigerian businesses',
    'GHS' => 'Ghanaian businesses',
];
